Patches core tier
redskyops/redskyops-recipes pull request #16
Opened 2020-09-28 18:40 UTC by stephanie-rifai

update the recipes to default to the free-tier version of the experiment file and make use of patches for the paid version. Recipes changed: locust-metrics, voting-web-app, and elasticsearch. Elastic search also now includes a kustomize.

2020-09-29 18:03 UTC, jimschley commented on elasticsearch/advanced/README.md
> +In order to run this experiment you most have a paid version of Red Sky Ops. To upgrade visit our [pricing page](https://www.carbonrelay.com/pricing/).
s/most have/must have/

2020-09-29 18:08 UTC, jimschley commented on locust-metrics/advanced/README.md
> +In order to run this experiment you most have a paid version of Red Sky Ops. To upgrade visit our [pricing page](https://www.carbonrelay.com/pricing/).
s/most have/must have/

2020-09-29 18:10 UTC, jimschley commented on voting-webapp/advanced/README.md
> +In order to run this experiment you most have a paid version of Red Sky Ops. To upgrade visit our [pricing page](https://www.carbonrelay.com/pricing/).
s/most have/must have/

2020-09-29 18:12 UTC, jimschley requested changes
Looks good. Added single line comments for typos in READMEs.

2020-09-29 20:17 UTC, stephanie-rifai commented on elasticsearch/advanced/README.md
> +In order to run this experiment you most have a paid version of Red Sky Ops. To upgrade visit our [pricing page](https://www.carbonrelay.com/pricing/).
```suggestion
In order to run this experiment you must have a paid version of Red Sky Ops. To upgrade visit our [pricing page](https://www.carbonrelay.com/pricing/).
```

2020-09-29 20:18 UTC, stephanie-rifai commented on voting-webapp/advanced/README.md
> +In order to run this experiment you most have a paid version of Red Sky Ops. To upgrade visit our [pricing page](https://www.carbonrelay.com/pricing/).
```suggestion
In order to run this experiment you must have a paid version of Red Sky Ops. To upgrade visit our [pricing page](https://www.carbonrelay.com/pricing/).
```

2020-09-29 20:19 UTC, stephanie-rifai commented on locust-metrics/advanced/README.md
> +In order to run this experiment you most have a paid version of Red Sky Ops. To upgrade visit our [pricing page](https://www.carbonrelay.com/pricing/).
```suggestion
In order to run this experiment you must have a paid version of Red Sky Ops. To upgrade visit our [pricing page](https://www.carbonrelay.com/pricing/).
```

2020-09-29 20:19 UTC, stephanie-rifai commented on locust-metrics/advanced/README.md
> +In order to run this experiment you most have a paid version of Red Sky Ops. To upgrade visit our [pricing page](https://www.carbonrelay.com/pricing/).
nice catch - thanks!

2020-09-29 20:20 UTC, jimschley approved these changes

2020-09-30 15:43 UTC, Ofer-Idan commented on elasticsearch/experiment.yaml
> +          value: "2"
If we're not tuning replicas, should this just move from the experiment.yaml to the application manifests?

2020-10-02 15:36 UTC, merged